### ISSUE TITLE
terminal/miniterm not working with pyserial 3.0.1

### ISSUE THREAD

**Issue by kmpm** [kmpm/nodemcu-uploader#39]
ImportError: cannot import name NEWLINE_CONVERISON_MAP

__edited title__
Not just windows. It doesn't work in linux either

**Comment by kmpm** [comment]
Closed in 0.2.1
